'use client';

import { useState, useRef, useEffect } from 'react';

export interface StitchDesign {
  id: string;
  imageUrl: string;
  htmlUrl: string;
  title: string;
  description: string;
  createdAt: string;
}

interface StitchPanelProps {
  isOpen: boolean;
  onClose: () => void;
  onSelectDesign: (design: StitchDesign | null) => void;
  selectedDesign: StitchDesign | null;
  lastPrompt?: string;
}

export default function StitchPanel({
  isOpen,
  onClose,
  onSelectDesign,
  selectedDesign,
  lastPrompt,
}: StitchPanelProps) {
  const [prompt, setPrompt] = useState('');
  const [designs, setDesigns] = useState<StitchDesign[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  // Pre-fill prompt from last user message
  useEffect(() => {
    if (isOpen && lastPrompt && !prompt) {
      setPrompt(lastPrompt);
    }
  }, [isOpen, lastPrompt]);

  // Focus input when panel opens
  useEffect(() => {
    if (isOpen) {
      setTimeout(() => inputRef.current?.focus(), 300);
    }
  }, [isOpen]);

  const fetchScreens = async () => {
    try {
      const res = await fetch('/api/stitch', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'list_screens' }),
      });
      const data = await res.json();
      if (res.ok && data.screens && Array.isArray(data.screens)) {
        if (data.screens.length === 0) return; // don't wipe out if just starting

        setDesigns(prev => {
          const newDesigns = data.screens.map((s: any) => ({
            id: s.id || `stitch_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
            imageUrl: s.imageUrl || '',
            htmlUrl: s.htmlUrl || '',
            title: s.title || 'Untitled Design',
            description: '',
            createdAt: new Date().toISOString(),
          }));

          // Merge descriptions from existing designs if they exist to keep prompt text
          return newDesigns.map((nd: StitchDesign) => {
            const existing = prev.find(p => p.id === nd.id);
            if (existing && existing.description) {
              nd.description = existing.description;
            } else if (!nd.description) {
              nd.description = 'Generated by Stitch AI';
            }
            return nd;
          });
        });
      }
    } catch (err) {
      console.error('Failed to fetch screens', err);
    }
  };

  // Poll screens on open and periodically (Stitch generation is asynchronous)
  useEffect(() => {
    if (!isOpen) return;
    
    fetchScreens();
    const interval = setInterval(fetchScreens, 15000);
    return () => clearInterval(interval);
  }, [isOpen]);

  const generateDesign = async () => {
    if (!prompt.trim() || isGenerating) return;
    setIsGenerating(true);
    setError(null);

    try {
      const res = await fetch('/api/stitch', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'generate',
          prompt: prompt.trim(),
        }),
      });

      const data = await res.json();

      if (!res.ok || data.error) {
        throw new Error(data.error || `Request failed: ${res.status}`);
      }

      // 1. First append a temporary card if we got a text response but no screens yet
      if ((!data.screens || data.screens.length === 0) && data.text) {
        setDesigns(prev => [{
          id: `stitch_${Date.now()}`,
          imageUrl: '',
          htmlUrl: '',
          title: `Design: ${prompt.trim().slice(0, 40)}`,
          description: data.text.slice(0, 500) + ' (Images rendering...)',
          createdAt: new Date().toISOString(),
        }, ...prev]);
      }

      // 2. Fetch screens immediately to see if any are ready
      await fetchScreens();

    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Unknown error';
      setError(msg);
    } finally {
      setIsGenerating(false);
    }
  };

  const clearAllDesigns = async () => {
    try {
      await fetch('/api/stitch', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'clear' }),
      });
      setDesigns([]);
      onSelectDesign(null);
      setPrompt('');
      setError(null);
    } catch (err) {
      console.error('Failed to clear designs', err);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      generateDesign();
    }
    if (e.key === 'Escape') {
      onClose();
    }
  };

  const toggleDesignSelection = (design: StitchDesign) => {
    if (selectedDesign?.id === design.id) {
      onSelectDesign(null);
    } else {
      onSelectDesign(design);
    }
  };

  return (
    <div className={`stitch-panel ${isOpen ? 'open' : ''}`}>
      {/* Backdrop */}
      <div className="stitch-backdrop" onClick={onClose} />

      <div className="stitch-panel-inner">
        {/* Header */}
        <div className="stitch-header">
          <div className="stitch-header-left">
            <span className="stitch-header-icon">🧵</span>
            <span className="stitch-header-title">Stitch Designs</span>
            <span className="stitch-badge-beta">BETA</span>
          </div>
          <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
            {designs.length > 0 && (
              <button
                className="stitch-close-btn"
                onClick={clearAllDesigns}
                title="Clear all designs"
                style={{ padding: '0 8px', width: 'auto', fontSize: '11px' }}
              >
                Clear All
              </button>
            )}
            <button className="stitch-close-btn" onClick={onClose} title="Close panel">
              ✕
            </button>
          </div>
        </div>

        {/* Generate Section */}
        <div className="stitch-generate-section">
          <div className="stitch-input-wrap">
            <input
              ref={inputRef}
              className="stitch-input"
              type="text"
              placeholder="Describe a UI design..."
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              onKeyDown={handleKeyDown}
              disabled={isGenerating}
            />
            <button
              className="stitch-generate-btn"
              onClick={generateDesign}
              disabled={!prompt.trim() || isGenerating}
            >
              {isGenerating ? (
                <span className="stitch-btn-spinner" />
              ) : (
                '✦ Generate'
              )}
            </button>
          </div>
          <p className="stitch-hint">
            Powered by Google Stitch AI — may take up to a minute
          </p>
        </div>

        {/* Error */}
        {error && (
          <div className="stitch-error">
            <span>⚠️</span>
            <span>{error}</span>
            <button onClick={() => setError(null)}>✕</button>
          </div>
        )}

        {/* Loading Skeletons */}
        {isGenerating && (
          <div className="stitch-skeleton-grid">
            {[0, 1, 2].map(i => (
              <div key={i} className="stitch-skeleton-card" style={{ animationDelay: `${i * 0.15}s` }}>
                <div className="stitch-skeleton-image" />
                <div className="stitch-skeleton-text" />
                <div className="stitch-skeleton-text short" />
              </div>
            ))}
          </div>
        )}

        {/* Design Gallery */}
        <div className="stitch-gallery">
          {designs.length === 0 && !isGenerating && (
            <div className="stitch-empty">
              <div className="stitch-empty-icon">🎨</div>
              <p className="stitch-empty-title">No designs yet</p>
              <p className="stitch-empty-desc">
                Describe a UI above and Stitch will generate beautiful mockup variations for your app.
              </p>
            </div>
          )}

          {designs.map((design) => (
            <div
              key={design.id}
              className={`stitch-card ${selectedDesign?.id === design.id ? 'selected' : ''}`}
              onClick={() => toggleDesignSelection(design)}
            >
              {design.imageUrl ? (
                <div className="stitch-card-image">
                  <img
                    src={design.imageUrl}
                    alt={design.title}
                    loading="lazy"
                    referrerPolicy="no-referrer"
                  />
                </div>
              ) : (
                <div className="stitch-card-placeholder">
                  <span>🧵</span>
                </div>
              )}
              <div className="stitch-card-info">
                <span className="stitch-card-title">{design.title}</span>
                <span className="stitch-card-desc">
                  {design.description.length > 80
                    ? design.description.slice(0, 80) + '…'
                    : design.description}
                </span>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '2px' }}>
                  <span className="stitch-card-time">
                    {new Date(design.createdAt).toLocaleTimeString()}
                  </span>
                  {design.htmlUrl && (
                    <a
                      href={`/api/stitch/preview?url=${encodeURIComponent(design.htmlUrl)}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="stitch-card-link"
                      onClick={(e) => e.stopPropagation()}
                      style={{ fontSize: '10px', color: 'var(--amber)', textDecoration: 'none' }}
                    >
                      View Live ↗
                    </a>
                  )}
                </div>
              </div>
              {selectedDesign?.id === design.id && (
                <div className="stitch-card-check">✓</div>
              )}
            </div>
          ))}
        </div>

        {/* Selected Design Banner */}
        {selectedDesign && (
          <div className="stitch-selected-banner">
            <div className="stitch-selected-info">
              <span className="stitch-selected-dot" />
              <span>Design Reference Active</span>
            </div>
            <button
              className="stitch-selected-clear"
              onClick={() => onSelectDesign(null)}
            >
              ✕ Clear
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
